### ISSUE TITLE
Link 2 unclassified

### ISSUE THREAD

**Issue by Soeldner** [splitbrain/unb#1]
the link to http://newsboard.unclassified.de/ is unreachable. You could link to http://unclassified.software/de/apps/unb ...

This issue should also show that anyone interest in this piece software :-)

Thanks for uploading.

**Comment by splitbrain** [comment]
http://newsboard.unclassified.de/ works fine for me.

**Comment by Soeldner** [comment]
I have reported it separately to Yves Goergen :)

Quote Yves:

"Hello Dominik,
The site was temporarily unavailable and I have not noticed until now. Now she is back as usual reach. "

Everything OK :)
